[package]
name = "nsrt"
version = "0.1.0"
edition = "2024"
description = "A Rust driver for the NSRT_mk4 sound level meter"
repository = "https://github.com/brandonweeks/nsrt"
license = "Apache-2.0"

[dependencies]
serialport = "4.7.3"
thiserror = "2.0.16"

[lints.clippy]
style = "warn"
